
require('./assets/load/Loading');
require('./assets/scripts/BombEffectSc');
require('./assets/scripts/BrickSc');
require('./assets/scripts/CheckOverSc');
require('./assets/scripts/DelayDelSc');
require('./assets/scripts/GameOverSc');
require('./assets/scripts/GameSc');
require('./assets/scripts/GameTouchSc');
require('./assets/scripts/IceEffectSc');
require('./assets/scripts/IconCooldownSc');
require('./assets/scripts/MessageBoxSc');
require('./assets/scripts/Msger');
require('./assets/scripts/PropUISc');
require('./assets/scripts/SceneManagerSc');
require('./assets/scripts/SoundConctrollerSc');
require('./assets/scripts/SplinteringConctrollerSc');
require('./assets/scripts/StartSc');
require('./assets/scripts/WXManager');
